# Generated by Django 5.2.7 on 2025-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_prompts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='prompts.prompt'),
        ),
    ]
