# Generated by Django 5.2.7 on 2025-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_saved_prompts'),
        ('prompt_templates', '0003_prompttemplate_slug_alter_prompttemplate_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_templates',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='prompt_templates.prompttemplate'),
        ),
    ]
