# Generated by Django 5.2.7 on 2025-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template_text', models.TextField(help_text='Use placeholders like [business_name], [business_type], [business_location], [target_audience]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
