# Generated by Django 5.2.7 on 2025-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='tips',
            field=models.TextField(blank=True, help_text="Optional tips to display below the form. E.g. 'Target audience could be families, students, couples…'", null=True),
        ),
    ]
