# Generated by Django 5.2.7 on 2025-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_templates', '0002_prompttemplate_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
