# Generated by Django 5.2.7 on 2025-10-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_templates', '0003_prompttemplate_slug_alter_prompttemplate_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('seo', 'SEO'), ('social', 'Social Media'), ('blog', 'Blog & Content'), ('email', 'Email Marketing'), ('sales', 'Sales Pages'), ('local', 'Local Business'), ('ads', 'Advertising'), ('customer', 'Customer Engagement'), ('video', 'Video Scripts')], default='marketing', max_length=50),
        ),
    ]
